version: "3"
services:
  rp:
    container_name: rp
    depends_on:
      - app
    image: gigiozzz/curp:0.1.0
    build: 
      context: ./rp
      dockerfile: rp.Dockerfile
    ports:
      - 80:8080
    restart: always 
  app:
    container_name: app
    image: gigiozzz/cuapp:0.1.0
    build: 
      context: .
      dockerfile: app.Dockerfile
    restart: always