apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-ver.fullname" . }}-rp
  labels:
    {{- include "helm-ver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.rp.service.type }}
  ports:
    - port: {{ .Values.rp.service.port }}
      targetPort: http-rp
      nodePort: {{ .Values.rp.service.nodePort }}
      protocol: TCP
      name: http-rp
  selector:
    {{- include "helm-ver.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/components: rp
